apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  inbound:
    - name: Insights
      port: 8000
      type: REST
      networkVisibility: Public
      # Remove the /api prefix from the context
      context: /
      schemaFilePath: docs/swagger.yaml